### PR TITLE
added upload file output

### PR DESCRIPTION
**Pull request by marvin-bitterlich**
As mentioned in #14 I created some logging output in the format we need and will soon update the pull request to add an uploader.

### CODE REVIEW

**Comment by seikur0** [comment]
Hey, I'm okay with a tool as you described it, "an upload tool that is completely separate from the map, but useable for people". I thought you meant a separate program, which I would be fine with. I don't want it integrated into the main0.py though.

**Comment by marvin-bitterlich** [comment]
@seikur0 sorry but I had to add some output because I need some extra information. As long as you do not execute the collector nothing gets send.

**Comment by seikur0** [comment]
This seems very redundant to me, I want you to make an extra .py file, (just one, put the module inside), that I can include and that users can execute, if they want. This program would look for the spawn files in the resource folder, since these contain everything you need and upload them. That's what I would be okay with. Sorry, if I wasn't being clear about that before.

**Comment by marvin-bitterlich** [comment]
I checked your files and found they make some modifications to the timestamps, is that correct? Or are your files exactly the things received from protobuf?

**Comment by marvin-bitterlich** [comment]
I could write a small parser for your files but it would be important that they contain the unmodified server data.

**Comment by seikur0** [comment]
They are exactly the thing, but protobuf 3.0.something puts that one line syntax: ***\* inside, and the python api doesn't like that, I just commented that out with a script.

**Comment by marvin-bitterlich** [comment]
Awesome! 

Sorry for the misunderstanding, I will update my scripts and remove the part from main

Should I keep the small fixes I found?

**Comment by seikur0** [comment]
I do think, I already put the small fixes into the update, thanks for these. I'm new to python and didn't know that "Exception, e" was "doing it the old way".

**Comment by marvin-bitterlich** [comment]
@seikur0 One thing I still got:

I would have to delete/move old files so they won't get send every time you start upload. What is the preferred (for you) way to not annoy users?

**Comment by seikur0** [comment]
The preferred way would be to create an extra settings file in the res folder, that lists the already sent spawnfiles. They all look like this: spawns0.20160728_1351.json, where the first 0 is the worker id (could potentially be two or more digits) and the numbers after that the date/time (same digits every time). Don't get the spawns0.json file, as that wouldn't be complete, i.e. below 10 MB standard setting.

**Comment by marvin-bitterlich** [comment]
I would try to find all files with this regex: `^spawns[^0-9]*\..+\.json$` would that work and exclude all other files?

**Comment by marvin-bitterlich** [comment]
@seikur0 removed all things from main0 and I think it will work now. WIll have to accumulate enough data to see if the uploader really works :)

**Comment by marvin-bitterlich** [comment]
@seikur0 Working like a charm, you can merge this

PS: uploading your huge file atm :)

**Comment by seikur0** [comment]
Hey, a bug fix is needed, I got that message:

<<
Greetings friend,

may you help me with one problem? I'm collection data with the help of your script. Not I want to use the collector.py to see what happens but I get an error in line 150 saying invalid syntax (end='')

Whats wrong? Thanks in advance

**Comment by seikur0** [comment]
And also this: https://github.com/seikur0/PGO-mapscan-opt/issues/38

**Comment by marvin-bitterlich** [comment]
What version of python is the person using? I'll try to write version-agnostic code but sometimes things slip...

**Comment by seikur0** [comment]
2.7.12 I'd wager. That's also the version I'm using and I get the same error.

**Comment by marvin-bitterlich** [comment]
Fixed the invalid syntax in #41

**Pull request merged**
