### PR TITLE
Fixes https://github.com/seikur0/PGO-mapscan-opt/issues/103

### PR DESCRIPTION
**Pull request by c00ni**
Fixes 2x15min spawn handling and beautifies index.html

### CODE REVIEW

**Comment by c00ni** [comment]
Forgot to add a comment to https://github.com/seikur0/PGO-mapscan-opt/pull/104/commits/e48eebceccd437a00839f6d13c169353c1eead79

Informs user the Pokemon is on it's first of 2 15m sessions.
Also skips over redoing the infotext for non-2x15 spawns.

**Comment by seikur0** [comment]
I didn't directly merge it, because with the new indents it basically showed the whole file as replaced and it was hard to see the differences, but I moved the text update function to the end and made it the only text updating thing, so that is fixed now. "Informs user the Pokemon is on it's first of 2 15m sessions." Oh yeah let me add that as well.

**Comment by c00ni** [comment]
But but I made them 2 separate commits so you could follow what I did!
Anyway as long as it works now :)

**Comment by seikur0** [comment]
I saw what you did, but I wanted to have just one place, where that text is set. And also, just a slight difference, you put it into the loop, that goes through the data entries and it's better in the loop, that goes through the markers. The difference is, that it'll keep working, when the data stops being sent and also for doubled entries or something it won't get repeated (not really a problem right now).

Still, very good job in spotting that bug, I still don't know, how it worked before haha Thanks :)

**Pull request closed without merging**
