### PR TITLE
Telegram bot for PGO-mapscan-opt w/interactive buttons

### PR DESCRIPTION
**Pull request by nodex0**
Hey!

So I've been working on this for some time already, and thought of sharing it. It is a telegram bot for this map, that works similarly to pokesite. It is pretty configurable and has some nice features, but the biggest one is each user can customize his own notification configuration. So sharing the map with friends becomes easier and you don't receive notifications 3km away! Just needs the new .json to work.

### CODE REVIEW

**Comment by nodex0** [comment]
Sorry, too lazy to do another pull request but line 257 should be:

`send_message(chat_id, messages["location_received"] + " " + messages["actual_radius"].format(u_settings["radius"]), reply_markup=build_menu("main", u_settings))`

instead of

`send_message(chat_id, messages["location_received"] + " " + messages["actual_radius"].format(radius_by_default), reply_markup=build_menu("main", u_settings))`

**Comment by furier** [comment]
It is possible to do multiple commits for a pull request and the owner can squash them into one when merging.

**Comment by nodex0** [comment]
Yeah, this bot can send chinese characters (at least it seemed in a test I did with a random one xP), Also, not sure about adding a commit, I am new to this...

**Comment by CaptainPoireau** [comment]
Hello, everything is working fine when i'm using it in english. But it doesn't seem to work in french.
This is my translation: http://pastebin.com/Fv0cV56e.
I don't know why it's returning the error message for everything. Logs seems fine.

**Comment by nodex0** [comment]
Found the error! It should check for the messages of silence_from and silence_to the last, also theres one elif lacking the el! Fixing it

**Comment by nodex0** [comment]
Also, thanks CaptainPoireau for the french translation!

**Review by CaptainPoireau — CHANGES_REQUESTED** [review]
Typo fixed in french translation
"hidden_pokemon" : "Un {0} <b>caché</b> est découvert !",

**Comment by dikkedeur** [comment]
okay got this started, added the file and started it with python telebot.py, it loads up.
went to telegram added the bot as usual got the welcome message, then he asks me for my location, 
then i get this error in console of the telegrambot

[10:19:06] [l] Location received: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telepot/**init**.py", line 738, in collector
    callback(item)
  File "/usr/local/lib/python2.7/dist-packages/telepot/helper.py", line 839, in route
    return fn(msg, _args, *_kwargs)
  File "telebot.py", line 298, in on_chat_message
    u_settings = set_settings(msg['from']['id'], noti=chat_id, lat=msg['location']['latitude'], lng=msg['location']['longitude'], rad=radius_by_default, ign=map(int, ignored_by_default.split(",")), nick=nick, silence="")
ValueError: invalid literal for int() with base 10: ''

**Comment by nodex0** [comment]
It seems you have no pokemon ignored. I am commiting a fix, but in most cases this will saturate the bot xP

**Comment by dikkedeur** [comment]
yes indeed i have none ignored

**Comment by nodex0** [comment]
This should be an easy fix so I haven't tested it, hope it works!

**Comment by seikur0** [comment]
Okay, this is looking good, I have great plans with this. @nodex0 remember how you talked to botfather to make it set up the bot. I don't see, why this shouldn't be doable with this bot here. Like imagine any user wants messages and he'd look for your bot, message him. He'd get all commands back.

He'd send `/addme` and he'd be added to the notification list. He'd send `/addpokemon 1,2,3` to be notified about the first three pokemon from now on, he's send `/removepokemon 1,2` to only be notified about Venusaur after this, same with location and everything.

So I'd like you to add a pull request to the master+telegram_bot(dev) branch instead of the master branch. And mind the new readme to avoid conflicts.

Also one thing about your no ignored pokemon fix just now, it doesn't make sense to have this as string, since you're using json make it `[1,2,3,4]` instead of `"1,2,3,4"` and it'll be loaded directly as integer array. I'll probably change a lot of your code after I merged this, since I'm a picky coder :D So  sorry in advance :)

**Comment by dikkedeur** [comment]
Dutch translation ( kinda in a hurry so there might be bumps in it ^^ )

http://pastebin.com/46262rk0

edit: updates textfixes

**Comment by seikur0** [comment]
Integrated.

**Pull request closed without merging**
