### PR TITLE
Update collector

### PR DESCRIPTION
**Pull request by marvin-bitterlich**
I've updated the collector a bit to improve handling on errors and show a progress bar.

Also I added a .gitignore file to your repo because I noticed you checked in .pyc files which normally do not belong in a repo. If you want I can delete these files in the pull request

### CODE REVIEW

**Comment by seikur0** [comment]
The .gitignore file isn't really important to me, since I check in each file manually.

**Comment by marvin-bitterlich** [comment]
What I mean are files like this one: https://github.com/seikur0/PGO-mapscan-opt/blob/master/POGOProtos/Inventory_pb2.pyc

**Comment by seikur0** [comment]
Yeah, I just noticed them. Will they be deleted with the .gitignore file? Or is that just to prevent me from uploading them.

**Comment by marvin-bitterlich** [comment]
The .gitignore will prevent adding new files of these sorts but since they are in there already, you have to actively commit a delete.

**Comment by seikur0** [comment]
That's what I thought :/ Then it's not that useful to me.

**Pull request merged**
