### PR TITLE
Added logging to SQLite db

### PR DESCRIPTION
**Pull request by nadnerb33**

### CODE REVIEW

**Comment by seikur0** [comment]
Hey, about that line: "lprint('Duplicate encounter - not inserting into db')"
That's not good, becacuse you need the negative time till hidden encounters to have complete data for spawn points. So with that, you'd only get the first one and discard that encounter for the rest of the time, which may be up to 45 minutes after that. Also there are 2x15min spawns, that spawn twice a hour for 15 min with the same id and encounter id (only one catchable.) Same case, you'd lose information.

It may be fine for you, if you're only interesting in spawn tables and not in spawn point types, but other people who're using this may not be aware of the limitations.

So either you somehow make it work with sql or I can't merge that, sorry.

**Comment by nadnerb33** [comment]
The primary key of the table (and what causes it to be rejected) is spawnID, pokeID and time - not encounterID. 
I thought that would be unique, if not, all columns logged to spawns.txt are also logged to this db, so would just need a change of PK to determine only genuine duplicates. 
What PK configuration would you suggest?

**Comment by seikur0** [comment]
Time as in SpawnTime? Then it's good. I'd suggest a combination of encounterID and SpawnTime. For negatives SpawnTime will be always unique, because in my code it's calculated as Time plus one second and for positives, you get the entry only once (Well at this point in my code you wouldn't get them twice anyway ;), I also don't want to log duplicates.). spawnID and pokeID in a certain combination will be repeated often, so it's not really worth much as unique identifier in comparison to encounterID.

**Comment by nadnerb33** [comment]
Sorry, yes PK is on spawnID, pokeID,SpawnTime

```
CREATE TABLE Encounters (
    EncounterID TEXT,
    SpawnID INTEGER,
    PokeID  INTEGER,
    SpawnTime   NUMERIC,
    Time    NUMERIC,
    Time2Hidden NUMERIC,
    PRIMARY KEY(SpawnID,PokeID,SpawnTime)
)
```

**Comment by seikur0** [comment]
So since api access is working again, let's continue with this: EncounterID is of type NUMERIC too and why not make EncounterID and SpawnTime together the primary keys? For SpawnID INTEGER is probably too small. It's 43 bits large, so it needs to be NUMERIC as well from my understanding?

**Pull request closed without merging**
