### PR TITLE
Added argument for number of scans

### PR DESCRIPTION
**Pull request by nadnerb33**
x number of scans: main0.py -s x
Without -s or -s 0 would be the current behaviour i.e infinite number of scans

### CODE REVIEW

**Comment by seikur0** [comment]
Okay, I'll include that with some small changes and put it in the settings file as well. I already made some changes for the next update, so it's easier to include it directly instead of merging. Closed.

**Comment by nadnerb33** [comment]
Ok, no worries

**Comment by nadnerb33** [comment]
Just tried it and its not working
I think the line 175 should be 
`scannum = int(args.scannum)`

**Comment by seikur0** [comment]
You seem to be working with an outdated version there? Because line 178 is exactly that.

**Pull request closed without merging**
