### PR TITLE
send location to telegram instead of link to google maps.

### PR DESCRIPTION
**Pull request by syzspectroom**
send location direct into telegram chat using sendLocation method (https://core.telegram.org/bots/api#sendlocation)

### CODE REVIEW

**Comment by seikur0** [comment]
I'm not sure about this, do you have any experience on how much bandwith it takes? Because it should take much less to send a link instead of an image.

**Comment by syzspectroom** [comment]
i can't say how much bandwith it takes, but an image is extremely small.
here is example screenshot. 
screenshot_2016-09-09-18-11-10

**Comment by seikur0** [comment]
Hm, what happens, when you click on these image? Does it link to google maps?

**Comment by syzspectroom** [comment]
no. interactive map opens in popup.like this:
screenshot_2016-09-09-18-41-09

**Comment by seikur0** [comment]
Okay, approved :)

**Comment by dvdblg** [comment]
In the latest commit the notification returned to the old link system instead of this one

**Comment by seikur0** [comment]
Okay, rereverted :(

**Comment by jespera9900** [comment]
The PokeAlarm webhook surpress the location message notification sent to Telegram, so the only notification sent is the info about the pokemon. Much cleaner on the phones lock screen. Could you do this here?

**Pull request merged**
