### PR TITLE
Update iconSize in index.html

### PR DESCRIPTION
**Pull request by ProfessorPokes**
Change the iconSize and iconAnchor to reflect the scalesize

### CODE REVIEW

**Comment by seikur0** [comment]
The iconSize and iconAnchor don't need to be the same as the scalesize, the first two refer to the real icon and the last one scales all of these values.

**Comment by ProfessorPokes** [comment]
They don't need to reflect the scalesize, but they should so that the center of the renderd and visible icon matches the actual lat and long of the poke it displays. My mobile chrome was showing the icons (scaled to 0.5) as being in the upper left quadrant, with a "clickable area" 2x the size of the icon and extending down and to the right of the icon. This was also reproducible on the desktop by moving the cursor slowly away from the center of the displayed icon.

**Comment by seikur0** [comment]
That's weird, from the api documentation it should be sufficient to set the scalesize. Oh well I changed it, didn't directly merge that pull request, because you didn't define anchor(not sure if that's really needed) and the half values are probably better off being integer pixels, not sure, if that would have lead to an error.

**Comment by ProfessorPokes** [comment]
That's fine. I'll admit I'm a bit new to this and learning as I go.

As for an error, I have no idea, I assumed so if you used an odd number and divided by 2 and are left with a remainder.

Not that this really mattered, youll never have to go directly to the location of the spawn, the infoWindows also showed up off center of the icons and it was more for aesthetics.

**Comment by seikur0** [comment]
I'm new to this too. Phew finally everything is fixed now. By the way with that range reduction spawnpoint scanner should be even more viable now.

**Pull request closed without merging**
