### PR TITLE
add language "zh-HK" for HK Chinese

### PR DESCRIPTION
**Pull request by toshioson**
trying to add an non-ascii code language "zh-HK"

### CODE REVIEW

**Comment by toshioson** [comment]
Such error reported when I launch the main0.py and held there, help needed.

```
[+] Catch up phase, 0/2 complete.
[+] Time: 18:53:08, ID: 0, None, Range: 3300, Start: 18:53:08

[+] Phase complete: 2.0 %
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "main0.py", line 1696, in run
    wild.last_modified_timestamp_ms, mod_tth, wild.encounter_id))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in `range(128)

[+] Phase complete: 4.0 %
```

**Comment by seikur0** [comment]
Okay, try it with the update I just made. And if that bug is gone, I'll merge it.

**Comment by toshioson** [comment]
Used "git pull" to update and got following message.

```
remote: Counting objects: 10, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 10 (delta 4), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), done.
From https://github.com/seikur0/PGO-mapscan-opt
   e88bf19..84b5cda  master     -> origin/master
Updating e88bf19..84b5cda
Fast-forward
 main0.py    | 69 +++++++++++++++++++++++++++++++++++++++++--------------------
 pokesite.py | 15 +++++++++-----
 2 files changed, 57 insertions(+), 27 deletions(-)
```

Restart main0.py and ScanSite got following error message,

```
[+] Catch up phase, 0/2 complete.
[+] Time: 23:31:28, ID: 0, None, Range: 3300, Start: 23:31:28

[+] Phase complete: 2.0 %
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "main0.py", line 1721, in run
    wild.last_modified_timestamp_ms, mod_tth, wild.encounter_id))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
```

**Comment by toshioson** [comment]
Switching back to english got another error running main0.py which already went into silent mode,

```
[-] Connection Error during Telegram, error: (u'Bad Request: Can\'t parse message text: Unsupported start tag "br" at byte of
fset 78', 400, {u'error_code': 400, u'ok': False, u'description': u'Bad Request: Can\'t parse message text: Unsupported start
 tag "br" at byte offset 78'})
```

P.S. removed `<br>` in line 1775 and alert is now coming

**Comment by seikur0** [comment]
Okay now, I turned the br back into \n, you'd think it would take the `<br>` tag after the `<b>` tag, but oh well. And I also replaced the file open function, that writes encoded strings into files as ascii, which doesn't make sense at all.

Bottomline is, now it should work.

**Comment by toshioson** [comment]
Thanks, I have checked out main0.py and did a git pull and saw the update on main0.py.

But there is still something's wrong when I set the language to zh-HK in usersettings.json and got the following error message when launching main0.py.

@seikur0 Could you please take a look again? Thanks.

```
[+] Catch up phase, 0/2 complete.
[+] Time: 09:12:14, ID: 0, None, Range: 3300, Start: 09:12:14

[+] Phase complete: 2.0 %
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "main0.py", line 1735, in run
    lprint(u'[+] ({}) {} visible for {} seconds ({}m {} from you)'.format(wild.pokemon_data.pokemon_id, POKEMONS[wild.pokemon
_data.pokemon_id], int(mod_tth / 1000.0), distance, direction))
  File "main0.py", line 892, in lprint
    sys.stdout.write(str(message) + '\n')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-10: ordinal not in range(128)

[+] Phase complete: 4.0 %
```

**Comment by seikur0** [comment]
Oh yes, the lprint. Fixed.

**Comment by toshioson** [comment]
Thanks but sorry that another error popped up...

```
[+] Phase complete: 10.0 %
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "main0.py", line 1735, in run
    lprint(u'[+] ({}) {} visible for {} seconds ({}m {} from you)'.format(wild.pokemon_data.pokemon_id, POKEMONS[wild.pokemon
_data.pokemon_id], int(mod_tth / 1000.0), distance, direction))
  File "main0.py", line 892, in lprint
    sys.stdout.write(u'{}\n'.format(message))
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 9-10: character maps to <undefined>

[+] Phase complete: 12.0 %
```

**Comment by seikur0** [comment]
Okay now again.

**Comment by toshioson** [comment]
Thanks and zh-HK is  working smoothly, the pokemon filter list in browser, the info when clicking on the pokemon on the map are all with Chinese now. Waiting to see how Telegram alert will be sent and also would like to run for a bit more time before confirming everything is alright. 

Thanks for the great work!

Update: Telegram alerts are coming through with the pokemon's name in Chinese but the address is still in English. Have to add in main0.py additional lines of lang_code for zh-HK. 

@seikur0 Can I add it in this PR or I have to put up another PR for it?

**Comment by seikur0** [comment]
Just add it to this one.

**Comment by toshioson** [comment]
@seikur0 sorry for dummy question but how can I add the commit to this one?

**Comment by seikur0** [comment]
You probably just commit it to your master branch? I'm not that sure.

**Comment by toshioson** [comment]
Done, please take a look, thanks.

**Comment by seikur0** [comment]
Okay, merged :)

**Pull request merged**
